name: CI-workflow
on: 
  push
    branches: [ "curso-github-actions" ]

    jobs:
      workflow-ejemplo
        runs-on: ubuntu-latest
          steps:
            name: Hola mundo
              run: python script.py
              
