# This is a basic workflow to help you get started with Actions
name: Uso_de_triggers
run-name: ¡EStoy aprendiendo trigguers!

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #issue_comment: 
    #types: [created, deleted]

on: 
  issue_comment:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'
  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: 'Lenguaje favorito'
        default: Pyhton
        required: true
        type: choice
        options:
          - Python
          - JavaScript
          - Go
      nombre:
        description: 'Tu nombre'
        required: true
        default: Ade
        type: string       
  schedule:
    - cron: '15 22 * * *'
jobs:
  ejecuta_triggers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Definir nombre
        run: echo "USERNAME=$"{{ inputs.nombre }} >> $GITHUB.ENV
      - name: Definir Lenguaje
        run: echo "LANGUAGE=$"{{ inputs.lenguaje_favorito }} >> $GITHUB.ENV
      - name: Correr script
        run: python bienvenidos.py
          
  ejecucion_programada:
    #if: ${{ github.event.issue.pull_request }} 
    if: ${{ github.event_name != 'workflow_dispatch' }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir variable
        run: echo "USERNAME=$"{{ github.actor }} >> $GITHUB.ENV
    
    
    


