# This is a basic workflow to help you get started with Actions
name: Uso_de_triggers

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #issue_comment: 
    #types: [created, deleted]

on: issue_comment

jobs:
  pr_commented:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: PR comment
      run: |
      if: ${{ github.event.issue.pull_request }}
    


